name: Send full commit history to Discord

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Send all commits to Discord
        run: |
          COMMITS=$(git log --pretty=format:"- %h: %s")

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$(jq -n --arg text "$COMMITS" '{content: $text}')" \
          ${{ secrets.DISCORD_WEBHOOK }}
